export const myArray = [
    {
        name:'TEST',
        Server:'test.cnqn7uorvp97.us-east-2.rds.amazonaws.com',
        Port:'1433',
        Database:'DB_TRANSPORTEX',
        UserID:'usuariomovil',
        UserPwd:'Tran5p0rt3x_2008tlf',
    },
    {
        name:'DEMO',
        Server:'transportexdemo.cdswhzyeho3j.us-east-2.rds.amazonaws.com',
        Port:'1433',
        Database:'DB_TRANSPORTEX',
        UserID:'oscar',
        UserPwd:'12345678',
    },  
    {
        name:'EJEMPLO1',
        Server:'transportexdemo.cdswhzyeho3j.us-east-2.rds.amazonaws.com',
        Port:'1433',
        Database:'DB_TRANSPORTEX',
        UserID:'oscar',
        UserPwd:'12345678',
    },     
]