export const myArray = [
  {
    name:'COMA_MEX',
    Server:'148.223.222.226',
    Port:'1433',
    Database:'DB_TRANSPORTEX',
    UserID:'user_moviles',
    UserPwd:'ytsB7Yc2hEuaDNC',
  },
  {
    name: 'DEMO',
    Server: 'ec2-3-144-160-231.us-east-2.compute.amazonaws.com',
    Port: '1433',
    Database: 'DB_TRANSPORTEX',
    UserID: 'usr_movil',
    UserPwd: 'Tran5p0rt3X_2008tlf',
  },
  {
    name: 'MADECO_MEX',
    Server: 'madeco.cxwcckmgw667.us-east-2.rds.amazonaws.com',
    Port: '1433',
    Database: 'DB_TRANSPORTEX',
    UserID: 'usr_movil2',
    UserPwd: 'Tran5p0rt3X_2008tlf',
  },  
 {
    name: 'EMDOM_VEN',
    Server: 'ec2-3-138-157-245.us-east-2.compute.amazonaws.com',
    Port: '1433',
    Database: 'DB_TRANSPORTEX',
    UserID: 'usr_movil',
    UserPwd: 'Tran5p0rt3X_2008tlf',
  },             
 {
    name: 'CPS_PAN',
    Server: 'cps.ccysvfpsgntm.us-east-2.rds.amazonaws.com',
    Port: '1433',
    Database: 'DB_TRANSPORTEX',
    UserID: 'usr_movil',
    UserPwd: 'Tran5p0rt3X_2008tlf',
  },        
];
